name: Label using github token

on:
  workflow_dispatch:

jobs:
  label-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-label PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          author="gkodinov"
          # Check if author is in the developers team
          if gh api \
            -H "Accept: application/vnd.github+json" \
            "/orgs/MariaDB/teams/developers/members/$author" \
            >/dev/null 2>&1; then
            echo "Author is in developers team"
          else
            echo "Author is not in developers team"
          fi
